on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install necessary packages
        shell: bash 
        run: |
          cd artshop.client
          npm i
      - name: Check style
        shell: bash 
        run: |
          chmod +x script/helpers/*.sh
          chmod +x script/lint.sh
          ./script/lint.sh
      - name: Run unit tests
        shell: bash
        run: |
          chmod +x script/helpers/*.sh
          chmod +x script/test.sh
          ./script/test.sh ALL
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install necessary packages
        shell: bash
        run: |
          cd artshop.client
          npm i
      - name: Deploy
        shell: bash
        env:
          AWS_ID: ${{ secrets.AWS_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          chmod +x script/helpers/*.sh
          chmod +x script/lint.sh
          ./script/helpers/containerize.sh artshop:latest
          ./script/helpers/push.sh artshop:latest